/**
 * js/pro/soundscapes.js — ambient beds under the pacer.
 *
 * Six voice-free ambiences (rain, ocean, brown noise, low drone, forest, night)
 * generated by tools/make-soundscapes.mjs and listed in /audio/manifest.json.
 * Nothing here is recorded, sampled or spoken: the whole pack is synthesised, so
 * there is no third-party licence anywhere in it. See docs/AUDIO.md.
 *
 * How it plays
 * ------------
 * One page-wide player. It borrows the engine's own `AudioContext` from
 * js/app.js and connects to `audioSystem.masterGain`, so a bed sits underneath
 * the inhale/exhale cue tones rather than beside them, and one context serves
 * the whole page however many timers it carries.
 *
 * The 60-second beds are already seamless end-to-end, but Opus and AAC both add
 * a little encoder padding that a plain `loop = true` can expose as a tick. So
 * the player schedules overlapping copies with a 1.5-second equal-power
 * crossfade at each boundary, and falls back to `loop = true` if the browser
 * will not take a value curve.
 *
 * Rules it keeps
 * --------------
 *  - Never starts before a real user gesture. `data-autostart` alone is not one.
 *  - Pauses while the tab is hidden and picks up when it comes back.
 *  - Free tier gets one 20-second preview per bed per page load, then
 *    `requirePro('soundscapes')`. That preview never arms the bed for a future
 *    page load, so nobody is met by audio they did not ask for.
 *  - Choice and volume live in `localStorage` under `hmb.soundscape`.
 *  - Once a visitor is Pro the whole pack is copied into the `hmb-audio` Cache,
 *    so it works offline from activation rather than from first play. Nothing
 *    is cached here for a free visitor.
 *  - No Web Audio, no manifest, no decoder: the button simply does not appear.
 */

import { audioSystem } from '../app.js';
import { getFlag, setFlag } from '../storage.js';
import { isPro, onChange, requirePro as defaultRequirePro } from '../entitlements.js';

const MANIFEST_URL = '/audio/manifest.json';
const CACHE_NAME = 'hmb-audio';
const STORE_KEY = 'soundscape';

const PREVIEW_MS = 20000; // free tier
const CROSSFADE_SECONDS = 1.5;
const FADE_OUT_SECONDS = 0.6;
const DEFAULT_VOLUME = 0.5;
const MAX_DECODED = 2; // AudioBuffers held at once; a 60 s bed is ~11 MB

/* ========================================================================== *
 * State — one player for the page, one panel per timer instance
 * ========================================================================== */

let manifestPromise = null;
let beds = [];

const decoded = new Map(); // name -> AudioBuffer, capped at MAX_DECODED
const previewed = new Set(); // beds this page load has already previewed
const panels = new Set(); // { render, syncToggle }

let outputGain = null;
let loopHandle = null;
/** Bumped by every play and every stop, so a slow load cannot land too late. */
let playToken = 0;

let selected = null; // the chosen bed name
let volume = DEFAULT_VOLUME;
let armed = false; // ride the session start/stop events
let playing = false;
let busy = false; // a load is in flight
let statusText = '';
let gestureSeen = false;
let hiddenWhilePlaying = false;
let wired = false;

let previewTimer = 0;
let previewStartedAt = 0;
let previewElapsed = 0;

let requirePro = defaultRequirePro;

/* ========================================================================== *
 * Persistence
 * ========================================================================== */

function loadState() {
  let raw = null;
  try {
    raw = getFlag(STORE_KEY);
  } catch {
    raw = null;
  }
  if (typeof raw !== 'string' || !raw) return;
  try {
    const parsed = JSON.parse(raw);
    if (parsed && typeof parsed === 'object') {
      if (typeof parsed.name === 'string') selected = parsed.name;
      if (typeof parsed.volume === 'number' && parsed.volume >= 0 && parsed.volume <= 1) {
        volume = parsed.volume;
      }
      armed = parsed.on === true;
    }
  } catch {
    /* a corrupt value is simply ignored */
  }
}

function saveState() {
  try {
    // `on` is only ever persisted for a paying visitor. A free visitor's
    // twenty-second preview must not arm the bed for every future page load:
    // that would start audio nobody asked for at the top of the next session
    // and then raise the paywall again the moment it expired. Their choice and
    // volume are still remembered, so pressing play again picks up where they
    // left off.
    const on = armed && isPro();
    setFlag(STORE_KEY, JSON.stringify({ name: selected, volume: Number(volume.toFixed(3)), on }));
  } catch {
    /* storage is optional */
  }
}

/* ========================================================================== *
 * Manifest and file choice
 * ========================================================================== */

function canPlay(type) {
  try {
    const probe = document.createElement('audio');
    if (!probe.canPlayType) return false;
    return probe.canPlayType(type) !== '';
  } catch {
    return false;
  }
}

/**
 * Candidate URLs for one bed, best first. Opus in Ogg is smaller and is what
 * every current browser except older Safari prefers; the AAC copy exists for
 * exactly that case. Decoding is retried down the list, because
 * `canPlayType` describes the media element and `decodeAudioData` is a
 * separate code path in some browsers.
 */
function urlsFor(entry) {
  const files = (entry && entry.files) || {};
  const ogg = typeof files.ogg === 'string' ? files.ogg : null;
  const m4a = typeof files.m4a === 'string' ? files.m4a : null;
  const wav = typeof files.wav === 'string' ? files.wav : null;
  const preferOgg = canPlay('audio/ogg; codecs="opus"');
  const ordered = preferOgg ? [ogg, m4a, wav] : [m4a, ogg, wav];
  return ordered.filter(Boolean);
}

async function loadManifest() {
  if (manifestPromise) return manifestPromise;
  manifestPromise = (async () => {
    let response = null;
    try {
      const cache = await caches.open(CACHE_NAME);
      response = await cache.match(MANIFEST_URL);
    } catch {
      response = null;
    }
    if (!response) response = await fetch(MANIFEST_URL, { credentials: 'omit' });
    if (!response || !response.ok) throw new Error('manifest unavailable');
    const data = await response.json();
    const list = Array.isArray(data) ? data : Array.isArray(data && data.beds) ? data.beds : [];
    beds = list.filter((entry) => entry && typeof entry.name === 'string' && urlsFor(entry).length);
    return beds;
  })().catch((error) => {
    manifestPromise = null;
    throw error;
  });
  return manifestPromise;
}

function bedByName(name) {
  return beds.find((entry) => entry.name === name) || null;
}

/* ========================================================================== *
 * Audio graph
 * ========================================================================== */

function supported() {
  if (!audioSystem || !audioSystem.isSupported) return false;
  if (typeof window === 'undefined') return false;
  return typeof fetch === 'function';
}

/** Start the shared context — only ever from inside a user gesture. */
async function ensureContext() {
  if (!supported()) return null;
  if (!audioSystem.isInitialized) await audioSystem.init();
  const ctx = audioSystem.audioContext;
  if (!ctx) return null;
  if (ctx.state === 'suspended') {
    try {
      await ctx.resume();
    } catch {
      /* the browser will let it through on the next gesture */
    }
  }
  if (ctx.state === 'suspended') return null;

  if (!outputGain || outputGain.context !== ctx) {
    outputGain = ctx.createGain();
    outputGain.gain.value = volume * routeTrim();
    // Under the cue tones: masterGain is where every engine sound already goes.
    outputGain.connect(audioSystem.masterGain || ctx.destination);
  }
  return ctx;
}

/**
 * masterGain already sits at 0.3, so a bed routed through it needs headroom
 * back. Routed straight to the destination it needs the opposite.
 */
function routeTrim() {
  return audioSystem && audioSystem.masterGain ? 1.8 : 0.55;
}

/**
 * The volume slider, and only the volume slider. Fades in and out belong to the
 * loop handle's own gain, so changing beds never interacts with the slider.
 */
function applyVolume() {
  if (!outputGain) return;
  const ctx = audioSystem.audioContext;
  const target = volume * routeTrim();
  try {
    outputGain.gain.setTargetAtTime(target, ctx ? ctx.currentTime : 0, 0.05);
  } catch {
    outputGain.gain.value = target;
  }
}

function equalPowerCurve(rising) {
  const points = 65;
  const curve = new Float32Array(points);
  for (let i = 0; i < points; i++) {
    const t = i / (points - 1);
    curve[i] = rising ? Math.sin((t * Math.PI) / 2) : Math.cos((t * Math.PI) / 2);
  }
  return curve;
}

const RISE = equalPowerCurve(true);
const FALL = equalPowerCurve(false);

/**
 * Loop a buffer with a crossfade at the seam.
 *
 * Overlapping copies are scheduled one period ahead — period is the buffer
 * minus the crossfade — each fading in and out on an equal-power curve. A
 * one-second pump keeps roughly four seconds of schedule ahead of the clock.
 */
function startLoop(ctx, buffer) {
  const duration = buffer.duration;
  const live = new Set();

  // One gain for the whole loop, so a fade-out is independent of the slider.
  const loopGain = ctx.createGain();
  loopGain.gain.value = 1;
  loopGain.connect(outputGain);

  let alive = true;
  let timer = 0;

  function teardown(fadeSeconds) {
    if (!alive) return;
    alive = false;
    window.clearInterval(timer);

    const now = ctx.currentTime;
    const fade = Math.max(0.02, fadeSeconds);
    try {
      loopGain.gain.cancelScheduledValues(now);
      loopGain.gain.setValueAtTime(loopGain.gain.value, now);
      loopGain.gain.linearRampToValueAtTime(0, now + fade);
    } catch {
      loopGain.gain.value = 0;
    }
    for (const node of live) {
      try {
        node.src.stop(now + fade + 0.02);
      } catch {
        /* already stopped */
      }
    }
    window.setTimeout(
      () => {
        try {
          loopGain.disconnect();
        } catch {
          /* ignore */
        }
      },
      Math.round((fade + 0.3) * 1000),
    );
  }

  // Too short to be worth overlapping — a cue tone, or a truncated file.
  if (!(duration > CROSSFADE_SECONDS * 3)) {
    const src = ctx.createBufferSource();
    src.buffer = buffer;
    src.loop = true;
    src.connect(loopGain);
    const node = { src };
    live.add(node);
    src.onended = () => {
      live.delete(node);
      try {
        src.disconnect();
      } catch {
        /* ignore */
      }
    };
    src.start();
    return { stop: teardown };
  }

  const period = duration - CROSSFADE_SECONDS;
  let nextAt = ctx.currentTime + 0.06;

  function scheduleAt(at) {
    const src = ctx.createBufferSource();
    src.buffer = buffer;
    const gain = ctx.createGain();
    gain.gain.value = 0;
    src.connect(gain);
    gain.connect(loopGain);

    // Two separate attempts: a browser that refuses the fade-in must still get
    // its fade-out, or a copy plays at full gain forever underneath the next.
    let rose = false;
    try {
      gain.gain.setValueCurveAtTime(RISE, at, CROSSFADE_SECONDS);
      rose = true;
    } catch {
      // Some engines refuse value curves; a hard edge on an already-seamless
      // bed is far better than silence.
      gain.gain.value = 1;
    }
    try {
      gain.gain.setValueCurveAtTime(FALL, at + period, CROSSFADE_SECONDS);
    } catch {
      if (!rose) gain.gain.value = 1;
      // The source is stopped at the end of its period regardless, so a missing
      // fade-out is a hard edge, never a stuck copy.
    }

    const node = { src, gain };
    live.add(node);
    src.onended = () => {
      live.delete(node);
      try {
        src.disconnect();
        gain.disconnect();
      } catch {
        /* ignore */
      }
    };

    src.start(at);
    try {
      src.stop(at + period + CROSSFADE_SECONDS + 0.02);
    } catch {
      /* ignore */
    }
  }

  function pump() {
    if (!alive) return;
    const now = ctx.currentTime;
    // A stalled main thread (a long task, a throttled background tab that came
    // back) can leave the next boundary in the past. Scheduling a value curve
    // at a past time throws, which would drop the fades on that copy, so step
    // the boundary forward instead and take one hard edge.
    if (nextAt < now + 0.05) nextAt = now + 0.05;
    const horizon = now + 4;
    let guard = 0;
    while (nextAt < horizon && guard < 8) {
      scheduleAt(nextAt);
      nextAt += period;
      guard += 1;
    }
  }

  pump();
  timer = window.setInterval(pump, 1000);

  return { stop: teardown };
}

/* ========================================================================== *
 * Loading and caching
 * ========================================================================== */

function decodeAudio(ctx, bytes) {
  return new Promise((resolve, reject) => {
    let settled = false;
    let result;
    try {
      result = ctx.decodeAudioData(
        bytes,
        (buffer) => {
          if (!settled) {
            settled = true;
            resolve(buffer);
          }
        },
        (error) => {
          if (!settled) {
            settled = true;
            reject(error || new Error('decode failed'));
          }
        },
      );
    } catch (error) {
      reject(error);
      return;
    }
    if (result && typeof result.then === 'function') {
      result.then(
        (buffer) => {
          if (!settled) {
            settled = true;
            resolve(buffer);
          }
        },
        (error) => {
          if (!settled) {
            settled = true;
            reject(error);
          }
        },
      );
    }
  });
}

function rememberBuffer(name, buffer) {
  decoded.set(name, buffer);
  while (decoded.size > MAX_DECODED) {
    const oldest = decoded.keys().next().value;
    if (oldest === undefined || oldest === name) break;
    decoded.delete(oldest);
  }
}

async function fetchAsset(url) {
  try {
    const cache = await caches.open(CACHE_NAME);
    const hit = await cache.match(url);
    if (hit) return hit;
  } catch {
    /* no Cache API here */
  }
  const response = await fetch(url, { credentials: 'omit' });
  if (!response || !response.ok) throw new Error(`could not load ${url}`);
  return response;
}

/** Keep the chosen bed for offline use. Pro only, and never fatal. */
async function cacheForOffline(url, response) {
  if (!isPro()) return;
  try {
    const cache = await caches.open(CACHE_NAME);
    const hit = await cache.match(url);
    if (hit) return;
    // A response we already have in hand costs nothing to keep; `cache.add()`
    // would download the same file a second time.
    if (response && typeof response.clone === 'function') await cache.put(url, response.clone());
    else await cache.add(url);
  } catch {
    /* private mode, quota, no Cache API — the bed still plays online */
  }
}

/**
 * Put the whole pack in the `hmb-audio` cache once a visitor is Pro.
 *
 * BUILD_SPEC FEAT-12 asks for the pack to be cached on Pro activation only, and
 * for the audio to play with the device offline afterwards. Caching lazily on
 * first play is not enough for that: someone who activates on the train and
 * then loses signal has nothing. So this runs in the background for a paying
 * visitor, one file at a time, preferring the format this browser will actually
 * decode. It is skipped entirely for a free visitor, which is what keeps the
 * free-tier cache exactly as small as it is today.
 *
 * It re-checks on every load rather than trusting a "done" flag, because the
 * service worker's `activate` handler deletes every cache whose name is not the
 * current shell cache — `hmb-audio` included — so the pack can disappear under
 * us on any deploy. Files already present are skipped, so the re-check is free.
 */
let warming = null;

function warmCache() {
  if (warming) return warming;
  if (!isPro()) return Promise.resolve();
  if (typeof caches === 'undefined') return Promise.resolve();
  if (typeof navigator !== 'undefined') {
    if (navigator.onLine === false) return Promise.resolve();
    const connection = navigator.connection;
    // Respect an explicit "save data" preference; the bed still plays online.
    if (connection && connection.saveData === true) return Promise.resolve();
  }

  warming = (async () => {
    try {
      await loadManifest();
      const cache = await caches.open(CACHE_NAME);
      // The list itself, so the panel can be built with the device offline.
      if (!(await cache.match(MANIFEST_URL))) await cache.add(MANIFEST_URL);
      for (const entry of beds) {
        if (!isPro()) return; // a licence removed mid-run stops the download
        const url = urlsFor(entry)[0];
        if (!url) continue;
        if (await cache.match(url)) continue;
        await cache.add(url);
      }
    } catch {
      /* offline, quota, private mode — nothing here is required to play */
    } finally {
      warming = null;
    }
  })();
  return warming;
}

async function bufferFor(ctx, entry) {
  const cached = decoded.get(entry.name);
  if (cached) return { buffer: cached, url: null };

  let lastError = null;
  for (const url of urlsFor(entry)) {
    try {
      const response = await fetchAsset(url);
      // Clone before the body is read, so the copy kept for offline use costs
      // no second download.
      const keep = typeof response.clone === 'function' ? response.clone() : null;
      const bytes = await response.arrayBuffer();
      const buffer = await decodeAudio(ctx, bytes);
      rememberBuffer(entry.name, buffer);
      return { buffer, url, response: keep };
    } catch (error) {
      lastError = error;
    }
  }
  throw lastError || new Error('no playable file');
}

/* ========================================================================== *
 * Preview timer (free tier)
 * ========================================================================== */

function clearPreview() {
  if (previewTimer) {
    window.clearTimeout(previewTimer);
    previewTimer = 0;
  }
}

function startPreviewTimer(fresh) {
  clearPreview();
  if (isPro()) return;
  if (fresh) previewElapsed = 0;
  const remaining = Math.max(0, PREVIEW_MS - previewElapsed);
  previewStartedAt = Date.now();
  previewTimer = window.setTimeout(() => {
    previewTimer = 0;
    endPreview();
  }, remaining);
}

function pausePreviewTimer() {
  if (!previewTimer) return;
  previewElapsed += Date.now() - previewStartedAt;
  clearPreview();
}

function endPreview() {
  const name = selected;
  if (name) previewed.add(name);
  stop({ remember: false, silent: true });
  setStatus('Preview finished. Soundscapes are part of Pro.');
  requirePro('soundscapes');
  renderAll();
}

/* ========================================================================== *
 * Transport
 * ========================================================================== */

function setStatus(text) {
  statusText = text || '';
  for (const panel of panels) panel.status(statusText);
}

/**
 * Start a bed.
 * @param {string} name
 * @param {{gesture?:boolean, resumed?:boolean}} [options] `gesture` marks a
 *        call that came straight out of a click or key press.
 */
async function play(name, options = {}) {
  if (!supported()) return false;
  if (!name) return false;
  if (!gestureSeen && options.gesture !== true) return false; // no autoplay, ever

  const paid = isPro();
  if (!paid && !options.resumed && previewed.has(name)) {
    setStatus('That was the preview. Soundscapes are part of Pro.');
    requirePro('soundscapes');
    renderAll();
    return false;
  }

  if (playing && selected === name) return true;
  if (playing) stop({ remember: true, silent: true, fade: 0.25 });

  const token = ++playToken;
  selected = name;
  armed = true;
  saveState();
  busy = true;
  setStatus('Loading…');
  renderAll();

  try {
    await loadManifest();
    const entry = bedByName(name);
    if (!entry) throw new Error('unknown soundscape');

    const ctx = await ensureContext();
    if (!ctx) {
      busy = false;
      setStatus('Audio is not available in this browser.');
      renderAll();
      return false;
    }

    const { buffer, url, response } = await bufferFor(ctx, entry);
    // The visitor changed their mind, or the session ended, while it loaded.
    if (token !== playToken || selected !== name) {
      busy = false;
      renderAll();
      return false;
    }

    loopHandle = startLoop(ctx, buffer);
    playing = true;
    busy = false;
    applyVolume();

    if (paid) {
      if (url) void cacheForOffline(url, response);
      void warmCache();
      setStatus(`Playing ${entry.label || entry.name}.`);
    } else {
      // Spend the preview the moment it starts, so stopping at nineteen seconds
      // and pressing play again is not an unlimited free bed.
      previewed.add(name);
      startPreviewTimer(!options.resumed);
      setStatus(`Playing ${entry.label || entry.name} — a 20 second preview.`);
    }
    renderAll();
    return true;
  } catch (error) {
    busy = false;
    playing = false;
    setStatus('That soundscape could not be loaded. Check your connection and try again.');
    renderAll();
    return false;
  }
}

/**
 * Stop playback.
 * @param {{remember?:boolean, silent?:boolean, fade?:number}} [options]
 *        `remember: true` keeps the bed armed, so the next session starts it
 *        again; `fade` overrides the fade-out length in seconds.
 */
function stop(options = {}) {
  pausePreviewTimer();
  if (options.remember !== true) {
    armed = false;
    saveState();
  }

  // Cancels a load that has not landed yet, as well as what is audible now.
  playToken += 1;
  playing = false;
  busy = false;

  const handle = loopHandle;
  loopHandle = null;
  if (handle) {
    try {
      handle.stop(typeof options.fade === 'number' ? options.fade : FADE_OUT_SECONDS);
    } catch {
      /* ignore */
    }
  }

  if (options.silent !== true) {
    setStatus('');
    renderAll();
  }
}

/* ========================================================================== *
 * Page-level wiring
 * ========================================================================== */

function noteGesture() {
  gestureSeen = true;
}

function wireOnce() {
  if (wired || typeof document === 'undefined') return;
  wired = true;

  document.addEventListener('pointerdown', noteGesture, { capture: true, once: true });
  document.addEventListener('keydown', noteGesture, { capture: true, once: true });
  document.addEventListener('touchend', noteGesture, { capture: true, once: true });

  document.addEventListener('hmb:session-start', () => {
    if (playing || busy) return;
    if (!armed || !selected) return;
    // A free visitor who has already spent that bed's preview is not asked
    // again at the top of every session. The panel is where they reach for it.
    if (!isPro() && previewed.has(selected)) return;
    void play(selected);
  });

  const end = () => {
    if (!playing && !busy) return;
    stop({ remember: true });
  };
  document.addEventListener('hmb:session-complete', end);
  document.addEventListener('hmb:session-stop', end);

  document.addEventListener('visibilitychange', () => {
    if (document.visibilityState === 'hidden') {
      if (!playing) return;
      hiddenWhilePlaying = true;
      stop({ remember: true, silent: true });
      setStatus('Paused while this tab is in the background.');
      renderAll();
    } else if (hiddenWhilePlaying) {
      hiddenWhilePlaying = false;
      // Coming back to a tab is not a user gesture, and it does not need to be:
      // the bed was already playing, so a gesture has already been seen.
      if (selected && armed) void play(selected, { resumed: true });
    }
  });

  onChange(() => {
    if (isPro()) {
      // A licence arriving mid-preview turns it into the real thing.
      clearPreview();
      previewed.clear();
      previewElapsed = 0;
      // FEAT-12: the pack is cached on Pro activation, not on first play.
      void warmCache();
    } else if (playing) {
      // A licence that lapsed stops the bed rather than leaving a paid feature
      // running for free.
      if (selected) previewed.add(selected);
      stop({ remember: false, silent: true });
      setStatus('Soundscapes are part of Pro.');
    }
    renderAll();
  });
}

/* ========================================================================== *
 * UI
 * ========================================================================== */

let uid = 0;

function el(tag, className, text) {
  const node = document.createElement(tag);
  if (className) node.className = className;
  if (text !== undefined) node.textContent = text;
  return node;
}

function renderAll() {
  for (const panel of panels) panel.render();
}

/**
 * Add the Soundscapes tool to one timer instance.
 *
 * @param {Element} rootEl the `[data-breathing-app]` element
 * @param {{requirePro?:Function, track?:Function}} [options] injected by
 *        js/pro/index.js. `track` is accepted for interface parity; the paywall
 *        module already reports `paywall_view` for this feature and `EVENTS`
 *        carries no soundscape-specific name, so nothing extra is sent.
 */
export function initSoundscapes(rootEl, options = {}) {
  if (!rootEl || typeof document === 'undefined') return;
  if (rootEl.dataset.proSoundscapes === 'on') return;

  // No Web Audio, no button. The timer is unchanged.
  if (!supported()) return;

  // Crisis-safe pages carry no ask at all, so a free visitor sees no locked
  // control there. A paying visitor keeps the feature.
  const quiet = !!(document.body && document.body.dataset && document.body.dataset.noAsks === 'true');
  if (quiet && !isPro()) return;

  // Look the slot up before claiming the root: a root without a tools slot must
  // stay eligible, so a later sweep can attach once the markup is complete.
  const tools = rootEl.querySelector('[data-slot="tools"]');
  if (!tools) return;

  rootEl.dataset.proSoundscapes = 'on';

  if (typeof options.requirePro === 'function') requirePro = options.requirePro;
  if (!panels.size) loadState();
  wireOnce();

  // An already-activated visitor arriving on a fresh page load: make sure the
  // pack is on the device before they need it offline.
  if (isPro()) void warmCache();

  const id = `soundscapes-${++uid}`;

  const toggle = el('button', 'tool-btn', 'Soundscapes');
  toggle.type = 'button';
  toggle.setAttribute('aria-expanded', 'false');
  toggle.setAttribute('aria-controls', id);
  const pill = el('span', 'pro-pill', 'Pro');
  pill.setAttribute('aria-hidden', 'true');
  pill.hidden = isPro();
  toggle.appendChild(pill);
  tools.appendChild(toggle);

  const panel = el('div', 'pro-panel');
  panel.id = id;
  panel.hidden = true;
  panel.setAttribute('data-pro-panel', 'soundscapes');
  tools.parentNode.insertBefore(panel, tools.nextSibling);

  const status = el('p', 'pro-panel-status');
  status.setAttribute('role', 'status');
  const list = el('ul', 'preset-items');
  let volumeInput = null;
  let volumeValue = null;
  let built = false;
  let loadError = false;

  function buildShell() {
    if (built) return;
    built = true;
    panel.innerHTML = '';
    panel.appendChild(el('h3', 'pro-panel-title', 'Soundscapes'));
    panel.appendChild(
      el(
        'p',
        'pro-panel-help',
        'Six ambiences, no voice and no music. They play under the breathing cues and stop when the session does.',
      ),
    );
    panel.appendChild(list);

    const grid = el('div', 'slider-grid');
    const row = el('div', 'slider-row');
    const label = el('label', 'slider-label', 'Volume');
    label.setAttribute('for', `${id}-volume`);
    volumeInput = document.createElement('input');
    volumeInput.type = 'range';
    volumeInput.id = `${id}-volume`;
    volumeInput.min = '0';
    volumeInput.max = '100';
    volumeInput.step = '1';
    volumeInput.value = String(Math.round(volume * 100));
    volumeValue = el('span', 'slider-value', `${Math.round(volume * 100)}%`);
    volumeInput.addEventListener('input', () => {
      volume = Math.max(0, Math.min(1, Number(volumeInput.value) / 100));
      applyVolume();
      saveState();
      for (const other of panels) other.syncVolume();
    });
    row.append(label, volumeInput, volumeValue);
    grid.appendChild(row);
    panel.appendChild(grid);

    panel.appendChild(status);
    panel.appendChild(
      el(
        'p',
        'pro-panel-help',
        'Every bed is generated by us from scratch: no recordings, no samples, no voice.',
      ),
    );

    const slot = el('div', '');
    slot.setAttribute('data-paywall-slot', '');
    panel.appendChild(slot);
  }

  function renderList() {
    list.innerHTML = '';
    if (loadError) {
      list.appendChild(el('li', 'pro-panel-help', 'The soundscape list could not be loaded. Try again in a moment.'));
      return;
    }
    if (!beds.length) {
      list.appendChild(el('li', 'pro-panel-help', 'Loading…'));
      return;
    }

    for (const entry of beds) {
      const item = el('li', 'preset-item');
      const button = el('button', 'preset-load');
      button.type = 'button';
      const isCurrent = playing && selected === entry.name;
      button.setAttribute('aria-pressed', String(isCurrent));
      button.appendChild(el('span', '', entry.label || entry.name));
      if (entry.description) {
        const hint = el('span', 'slider-label', ` ${entry.description}`);
        button.appendChild(hint);
      }
      button.addEventListener('click', () => {
        if (playing && selected === entry.name) {
          stop({ remember: false });
          return;
        }
        void play(entry.name, { gesture: true });
      });

      const state = el('span', 'slider-value', '');
      if (busy && selected === entry.name) state.textContent = '…';
      else if (isCurrent) state.textContent = 'Playing';
      else if (!isPro() && previewed.has(entry.name)) state.textContent = 'Pro';

      item.append(button, state);
      list.appendChild(item);
    }
  }

  const api = {
    render() {
      if (panel.hidden) {
        pill.hidden = isPro();
        return;
      }
      buildShell();
      renderList();
      pill.hidden = isPro();
      if (volumeInput) {
        volumeInput.value = String(Math.round(volume * 100));
        if (volumeValue) volumeValue.textContent = `${Math.round(volume * 100)}%`;
      }
      status.textContent = statusText;
    },
    status(text) {
      status.textContent = text;
    },
    syncVolume() {
      if (!volumeInput) return;
      volumeInput.value = String(Math.round(volume * 100));
      if (volumeValue) volumeValue.textContent = `${Math.round(volume * 100)}%`;
    },
  };
  panels.add(api);

  toggle.addEventListener('click', () => {
    const open = panel.hidden;
    panel.hidden = !open;
    toggle.setAttribute('aria-expanded', String(open));
    if (!open) return;

    buildShell();
    renderList();
    api.render();

    if (!beds.length && !loadError) {
      loadManifest()
        .then(() => {
          loadError = false;
          api.render();
        })
        .catch(() => {
          loadError = true;
          api.render();
        });
    }
  });
}

export default initSoundscapes;
